apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: dkg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.4.4
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          ports:
            - containerPort: 2181
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: dkg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      serviceAccountName: dependencies-sa
      initContainers:
        - name: check-pods-ready
          image: bitnami/kubectl
          command:
          - 'sh'
          - '-c'
          - >
            until kubectl get pods zookeeper-0 -n dkg -o jsonpath='{.status.phase}' | grep Running; do echo waiting for pods; sleep 5; done
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.4.4
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper.dkg.svc:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-clusterip.dkg.svc:9092,PLAINTEXT_HOST://10.18.1.40:30093"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          ports:
            - containerPort: 9092
            - containerPort: 29092
---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: dkg
spec:
  ports:
    - port: 2181
  selector:
    app: zookeeper

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-clusterip
  namespace: dkg
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
  namespace: dkg
spec:
  type: NodePort
  ports:
    - port: 29092
      targetPort: 29092
      nodePort: 30093
  selector:
    app: kafka




