apiVersion: v1
kind: Secret
metadata:
  name: neo4j-auth
  namespace: dkg
type: Opaque
data:
  NEO4J_AUTH: bmVvNGovcGFzc3dvcmQ=

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: dkg
spec:
  serviceName: neo4j
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      enableServiceLinks: false 
      containers:
        - name: neo4j
          image: neo4j:5.20.0
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: neo4j-auth
                  key: NEO4J_AUTH
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
  #         volumeMounts:
  #           - name: data
  #             mountPath: /data
  # volumeClaimTemplates:
  #   - metadata:
  #       name: data
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: dkg
spec:
  selector:
    app: neo4j
  ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: neo4j-pv
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /path/on/node/neo4j-data
